"use client";
import ContactInfo from "@/components/ConactInfo";
import "./globals.css";
// import type { Metadata } from "next";
import HeaderNavigation from "@/components/HeaderNavigation";
import HeroCarousel from "@/components/HeroCarousel";
import ElementorComponent from "@/components/ElementorComponent";
import AboutUs from "@/components/AboutUs";
import ServicveHero from "@/components/ServiceHero";
import ContactOptions from "@/components/ContactOptions";
import TestimonialsComponent from "@/components/TestimonialsComponent";

// export const metadata: Metadata = {
//   title: "Lemke - Gebäudereinigung",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body className="text-white min-h-screen">
        <ContactInfo />
        <HeaderNavigation />
        <HeroCarousel />
        <section className="w-full h-full services__background">
          <ElementorComponent />
          <AboutUs />
        </section>
        <ServicveHero />
        <TestimonialsComponent />
        <ContactOptions />
      </body>
    </html>
  );
}
