"use client";
import HeaderNavigation from "@/components/HeaderNavigation";
import FooterComponent from "@/components/FooterComponent";
import ContactInfo from "@/components/ConactInfo";

import "./globals.css";
// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Lemke - Gebäudereinigung",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body className="text-white min-h-screen min-w-screen">
        <ContactInfo />
        <HeaderNavigation />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
